version: "3"

services:
  influxdb:
    image: influxdb:2.1.1
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  grafana:
    image: grafana/grafana-oss:8.4.3
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000